import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// 1. import `NextUIProvider` component
import {NextUIProvider} from "@nextui-org/system";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}){
    // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}
      >
        <NextIntlClientProvider messages={messages}>
        <NextUIProvider>
        {children}
        </NextUIProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
